---
title: "Assignments"
---


## Weekly Summaries (20% of final grade)

Each week for eight weeks, you will summarize one of the readings (the one bolded in the corresponding topic page). That means you can skip some weeks. It is up to you which weeks you decide to skip. The summary must be no longer than three-quarters of a page (single-spaced, 12-point font). These summaries must be submitted via Canvas prior to class on the day for which the reading is assigned. No credit will be given for submissions after class has started.

You can find a brief guide on how to write a summary [here](../resource/summaries.html).


## Three Papers 

You will be writing three short papers (approx. 4-6 pages) throughout the course. These assignments will require you to think about how what we learn in class relates to what you can observe in your political environment (also known as the "real world"). You can find a short description of each paper below:

  1. <ins>*Congregational visit paper (4-6 pages):*</ins> students will attend two religious services of a religious tradition or denomination other than their own and will write about how politics is (or is not) addressed, directly or indirectly, in that particular congregation.
  
  2. <ins>*Campaign memo (4-6 pages, single-spaced):*</ins> students will write a campaign memo on the political attitudes and behaviors of Latinos/as. Students must provide sufficient background, provide clear takeaways, and propose strategies for a political campaign to appeal to Latino voters. The audience for this paper is a political campaign staff.
  
  3. <ins>*Op-ed (3-5 pages):*</ins> students will write an op-ed on a topic of their choice. Students must make a clear argument and use class material to help them organize their essays or provide context to the situation.

- Papers must be submitted via Canvas. Late submissions will be penalized: half a point (out of 10) if turned in late but on the same day and one point for each 24-hour period after the due date.




