---
title: "Mobilization and Vote Choice"
---

[//]: <> (Need to write intro)

## Monday, September 18

### Readings 

1. Putnam, Robert and David Campbell. 2010. "Religion in American Politics." *American Grace.* New York: Simon & Schuster. (Chapter 11: pp. 369-418.) {{< fa file-pdf >}} available on Canvas.

[<span class="btn btn-danger">{{< fa file-pdf >}} PDF of slides </span></p>](https://agnesscott.instructure.com/files/588573)


---


## Wednesday, September 20

1. Wald, Kenneth D., and David C. Leege. 2010. "Mobilizing religious differences in American politics." In *Religion and Democracy in the United States: Danger or Opportunity?* Alan Wolfe and Ira Katznelson (eds). Princeton, NJ: Princeton University Press. (Chapter 11: pp. 355-381.) {{< fa file-pdf >}} available on Canvas.

[<span class="btn btn-danger">{{< fa file-pdf >}} PDF of slides </span></p>](https://agnesscott.instructure.com/files/588574)


---


## Friday, September 22

No reading


---

:::{.callout-important}
Updated
:::


## Monday, September 25

1. **Kalkan, Kerem Ozan, Geoffrey C. Layman, and John C. Green. 2018. "Will Americans Vote for Muslims? Cultural Outgroup Antipathy, Candidate Religion, and U.S. Voting Behavior." *Politics and Religion* 11(4): 798–829.** [{{< fa university >}}](https://search.ebscohost.com/login.aspx?direct=true&AuthType=shib&db=poh&AN=132890314&site=eds-live&scope=site&custid=asc1)
 
 
---


## Wednesday, September 27

- Bring draft of congregational visit paper
- Peer reviews in class 


---

## Friday, September 29

- No assigned reading 
