---
title: "Latino Catholics, Latino Protestants, and Religious Minorities"
---

[//]: <> (Need to write intro)

## Monday, October 23

### Readings 

1. Leal, David L. 2010. "Religion and the Political and Civic Lives of Latinos." In *Religion and Democracy in the United States: Danger or Opportunity?* Alan Wolfe and Ira Katznelson (eds). Princeton, NJ: Princeton University Press. (Chapter 10: pp. 308-352.) {{< fa file-pdf >}} available on Canvas.




---


## Wednesday, October 25

### Readings 

1. Molina, Alejandra. 2020. "Latino Protestants More Conservative, Supportive of Trump than Latino Catholics, Poll Finds." *Religion News Service.* [{{< fa arrow-up-right-from-square >}}](https://religionnews.com/2020/12/01/latino-protestants-more-conservative-supportive-of-trump-than-latino-catholics-poll-finds/)


---


## Friday, October 27

### Readings 

1. **Hertzke, Allen D., Laura R. Olson, Kevin R. den Dulk, and Robert Booth Fowler. 2018. "Judaism, Islam, and Other Expressions of Religious Pluralism." *Religion and Politics in America: Faith, Culture, and Strategic Choices. 6th ed.* New York, NY: Routledge.** (Chapter 4.) {{< fa file-pdf >}} available on Canvas.


