---
title: "A Religious Left?"
---

[//]: <> (Need to write intro)

## Monday, November 13

### Readings 

1. Baker, Joseph O, and Gerardo Martí. 2020. "Is the Religious Left Resurgent?" *Sociology of Religion* 81(2): 131–41. [{{< fa university >}}](https://search.ebscohost.com/login.aspx?direct=true&AuthType=shib&db=rfh&AN=ATLAi5IE200720000033&site=eds-live&scope=site&custid=asc1)

2. Sager, Rebecca. 2017. "Progressive Religious Activists and Democratic Party Politics." In *Religion and Progressive Activism: New Stories about Faith and Politics*, eds, Ruth Braunstein, Todd Nicholas Fuist, and Rhys H. Williams. New York: New York University Press, 56-75. [{{< fa university >}}](https://search.ebscohost.com/login.aspx?direct=true&AuthType=shib&db=nlebk&AN=1367257&site=eds-live&scope=site&custid=asc1)


[<span class="btn btn-danger">{{< fa file-pdf >}} PDF of slides </span></p>](https://agnesscott.instructure.com/files/626953/download?download_frd=1)

---


## Wednesday, November 15

### Readings 

1. Olson, Laura R. 2017. "Collective Identity and Movement Solidarity among Religious Left Activists in the U.S." In *Religion and Progressive Activism: New Stories about Faith and Politics*, eds, Ruth Braunstein, Todd Nicholas Fuist, and Rhys H. Williams. New York: New York University Press, 97-114. [{{< fa university >}}](https://search.ebscohost.com/login.aspx?direct=true&AuthType=shib&db=nlebk&AN=1367257&site=eds-live&scope=site&custid=asc1)

    - Summarize one of the chapters assigned from this book.

---


## Friday, November 17

### Readings 

1. No assigned reading

 
