---
title: "Midterm Guide"
---

This is a list of concepts and frameworks with which you should be familiar for the midterm exam. You might be asked to define and/or apply any of these during the examination. You might not be directly asked about these terms, but they can help you answer some of the questions.

1.	Secularization theory
    1. Differentiation (privatization, desacralization, liberalization)
    2.	Modernization theory
    3.	Marxist theory
2.	Arguments for why religion is still an important phenomenon in the United States (see Wald and Calhoun-Brown)
3.	Religious composition of the major political parties
4.	The Three B's approach (believing, belonging, and behaving) and how to measure them
5.	Religious tradition classification, known as RELTRAD (how do scholars group individuals in religious affiliations)
6.	Putnam and Campbell's "shock" and two "aftershocks"
7.	Potential sources of religious influence
    1.	At the individual level
    2.	At the congregational level
8.	The establishment and free exercise clauses in the First Amendment
    1.	Lemon test
    2.	Strict scrutiny
    3.	Smith precedent
    4.	Ministerial exception
9.	Davis' (2001) framework of separation, integration, and accommodation
10.	What does it mean to study the intersection of religion and politics from a political science perspective?
11.	Normative and positivist approaches/statements
12.	The evolution of religious divisions ("conflict") in the twentieth century (to the present)
13.	Culture wars model
    1.	Is there a culture war?
    2.	The role of elites in mobilizing religious differences
14.	Church attendance and political participation
    1.	Why do people participate in politics?
    2.	How is involvement in a congregation connected to political participation?
15.	Black Protestants and the Black Church
    1.	Why do we talk about there being a Black Church? (think theological orientations, history, leadership)
    2.	Social Gospel, liberation theology, black theology vs. Prosperity Gospel
16.	Latino Catholics and Latino Protestants
    1.	Is there a Latino Church? (think theological orientations, history, leadership)
