---
title: Resources for Congregational Visit Paper
---

# Anatomy of an Empirical Research Paper

1. Introduction (establish what you are doing, the research question, and major conclusions)
2. Literature Review (situate your work in a conversation)
3. Theory (your explanation and expectations)
4. Data and Methods (how you collect and analyze data)
5. Results
6. Discussion and conclusion

# What Should this Paper Include?

1. Introduction (establish what you are doing, the research question, and major conclusions)
2. Importance of looking at congregational life
3. Methodology (how are you tackling the initial question?)
4. The congregation you are visiting and its religious tradition (provide some background on the congregation and its religious tradition - [use data](https://www.pewresearch.org/religion/religious-landscape-study/)
5. Expectations (what do you think you will find?)
6. Results (describe what you found during the service)
7. Discussion (do your results match your initial expectations?)
8. Conclusion (what do you think your results tell you about political stimuli in churches? Discuss limitations and ways to overcome them in future research)




